//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 02:32:19 PM IST 
//


package com.anz.cobolTransform.transform.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctTrnInqCTMRsp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctTrnInqCTMRsp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OutputHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServiceResponse">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                         &lt;maxLength value="24"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="VersionNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DataLength">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="99999999"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ServiceResultCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="999"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ErroMessage">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                         &lt;maxLength value="40"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ConditionCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="99999999"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SecondaryHdr">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProcessingApplication">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AccountNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                         &lt;maxLength value="23"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RegistrationNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                         &lt;maxLength value="23"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LinkageNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ServiceResponseMsg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NextTransactionStart">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="999999"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="NumberOfTransactions">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="OutputDetails" maxOccurs="50" minOccurs="50">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TransactionDateV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99999999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionTimeV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="999999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionSRCECODEV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionSRCEV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="20"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionAMTV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99999999999.99"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionCRINDV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionTypeCodeV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionTypeV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="20"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionBranchV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="9999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionNarrativeV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="40"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionSerialNoV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__long">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="9999999999999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionSourceV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
 *                                   &lt;maxLength value="4"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TransactionEffDateV2">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99999999"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctTrnInqCTMRsp", propOrder = {
    "serviceName",
    "outputHeader",
    "secondaryHdr",
    "serviceResponseMsg"
})
public class AcctTrnInqCTMRsp {

    @XmlElement(name = "ServiceName", required = true, defaultValue = " ")
    protected String serviceName;
    @XmlElement(name = "OutputHeader", required = true)
    protected AcctTrnInqCTMRsp.OutputHeader outputHeader;
    @XmlElement(name = "SecondaryHdr", required = true)
    protected AcctTrnInqCTMRsp.SecondaryHdr secondaryHdr;
    @XmlElement(name = "ServiceResponseMsg", required = true)
    protected AcctTrnInqCTMRsp.ServiceResponseMsg serviceResponseMsg;

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the outputHeader property.
     * 
     * @return
     *     possible object is
     *     {@link AcctTrnInqCTMRsp.OutputHeader }
     *     
     */
    public AcctTrnInqCTMRsp.OutputHeader getOutputHeader() {
        return outputHeader;
    }

    /**
     * Sets the value of the outputHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctTrnInqCTMRsp.OutputHeader }
     *     
     */
    public void setOutputHeader(AcctTrnInqCTMRsp.OutputHeader value) {
        this.outputHeader = value;
    }

    /**
     * Gets the value of the secondaryHdr property.
     * 
     * @return
     *     possible object is
     *     {@link AcctTrnInqCTMRsp.SecondaryHdr }
     *     
     */
    public AcctTrnInqCTMRsp.SecondaryHdr getSecondaryHdr() {
        return secondaryHdr;
    }

    /**
     * Sets the value of the secondaryHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctTrnInqCTMRsp.SecondaryHdr }
     *     
     */
    public void setSecondaryHdr(AcctTrnInqCTMRsp.SecondaryHdr value) {
        this.secondaryHdr = value;
    }

    /**
     * Gets the value of the serviceResponseMsg property.
     * 
     * @return
     *     possible object is
     *     {@link AcctTrnInqCTMRsp.ServiceResponseMsg }
     *     
     */
    public AcctTrnInqCTMRsp.ServiceResponseMsg getServiceResponseMsg() {
        return serviceResponseMsg;
    }

    /**
     * Sets the value of the serviceResponseMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctTrnInqCTMRsp.ServiceResponseMsg }
     *     
     */
    public void setServiceResponseMsg(AcctTrnInqCTMRsp.ServiceResponseMsg value) {
        this.serviceResponseMsg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ServiceResponse">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *               &lt;maxLength value="24"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="VersionNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DataLength">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="99999999"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ServiceResultCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="999"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ErroMessage">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *               &lt;maxLength value="40"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ConditionCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="99999999"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serviceResponse",
        "versionNumber",
        "dataLength",
        "serviceResultCode",
        "erroMessage",
        "conditionCode"
    })
    public static class OutputHeader {

        @XmlElement(name = "ServiceResponse", required = true, defaultValue = " ")
        protected String serviceResponse;
        @XmlElement(name = "VersionNumber", defaultValue = "0")
        protected int versionNumber;
        @XmlElement(name = "DataLength", defaultValue = "0")
        protected long dataLength;
        @XmlElement(name = "ServiceResultCode", defaultValue = "0")
        protected int serviceResultCode;
        @XmlElement(name = "ErroMessage", required = true, defaultValue = " ")
        protected String erroMessage;
        @XmlElement(name = "ConditionCode", defaultValue = "0")
        protected long conditionCode;

        /**
         * Gets the value of the serviceResponse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceResponse() {
            return serviceResponse;
        }

        /**
         * Sets the value of the serviceResponse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceResponse(String value) {
            this.serviceResponse = value;
        }

        /**
         * Gets the value of the versionNumber property.
         * 
         */
        public int getVersionNumber() {
            return versionNumber;
        }

        /**
         * Sets the value of the versionNumber property.
         * 
         */
        public void setVersionNumber(int value) {
            this.versionNumber = value;
        }

        /**
         * Gets the value of the dataLength property.
         * 
         */
        public long getDataLength() {
            return dataLength;
        }

        /**
         * Sets the value of the dataLength property.
         * 
         */
        public void setDataLength(long value) {
            this.dataLength = value;
        }

        /**
         * Gets the value of the serviceResultCode property.
         * 
         */
        public int getServiceResultCode() {
            return serviceResultCode;
        }

        /**
         * Sets the value of the serviceResultCode property.
         * 
         */
        public void setServiceResultCode(int value) {
            this.serviceResultCode = value;
        }

        /**
         * Gets the value of the erroMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErroMessage() {
            return erroMessage;
        }

        /**
         * Sets the value of the erroMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErroMessage(String value) {
            this.erroMessage = value;
        }

        /**
         * Gets the value of the conditionCode property.
         * 
         */
        public long getConditionCode() {
            return conditionCode;
        }

        /**
         * Sets the value of the conditionCode property.
         * 
         */
        public void setConditionCode(long value) {
            this.conditionCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProcessingApplication">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AccountNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *               &lt;maxLength value="23"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RegistrationNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *               &lt;maxLength value="23"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LinkageNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processingApplication",
        "accountNumber",
        "registrationNumber",
        "linkageNumber"
    })
    public static class SecondaryHdr {

        @XmlElement(name = "ProcessingApplication", required = true, defaultValue = " ")
        protected String processingApplication;
        @XmlElement(name = "AccountNumber", required = true, defaultValue = " ")
        protected String accountNumber;
        @XmlElement(name = "RegistrationNumber", required = true, defaultValue = " ")
        protected String registrationNumber;
        @XmlElement(name = "LinkageNumber", defaultValue = "0")
        protected int linkageNumber;

        /**
         * Gets the value of the processingApplication property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessingApplication() {
            return processingApplication;
        }

        /**
         * Sets the value of the processingApplication property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessingApplication(String value) {
            this.processingApplication = value;
        }

        /**
         * Gets the value of the accountNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountNumber(String value) {
            this.accountNumber = value;
        }

        /**
         * Gets the value of the registrationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistrationNumber() {
            return registrationNumber;
        }

        /**
         * Sets the value of the registrationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistrationNumber(String value) {
            this.registrationNumber = value;
        }

        /**
         * Gets the value of the linkageNumber property.
         * 
         */
        public int getLinkageNumber() {
            return linkageNumber;
        }

        /**
         * Sets the value of the linkageNumber property.
         * 
         */
        public void setLinkageNumber(int value) {
            this.linkageNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NextTransactionStart">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="999999"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="NumberOfTransactions">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="OutputDetails" maxOccurs="50" minOccurs="50">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TransactionDateV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99999999"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionTimeV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="999999"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionSRCECODEV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionSRCEV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionAMTV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99999999999.99"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionCRINDV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionTypeCodeV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionTypeV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionBranchV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="9999"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionNarrativeV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="40"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionSerialNoV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__long">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="9999999999999"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionSourceV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
     *                         &lt;maxLength value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TransactionEffDateV2">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99999999"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nextTransactionStart",
        "numberOfTransactions",
        "outputDetails"
    })
    public static class ServiceResponseMsg {

        @XmlElement(name = "NextTransactionStart", defaultValue = "0")
        protected long nextTransactionStart;
        @XmlElement(name = "NumberOfTransactions", defaultValue = "0")
        protected int numberOfTransactions;
        @XmlElement(name = "OutputDetails", required = true)
        protected List<AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails> outputDetails;

        /**
         * Gets the value of the nextTransactionStart property.
         * 
         */
        public long getNextTransactionStart() {
            return nextTransactionStart;
        }

        /**
         * Sets the value of the nextTransactionStart property.
         * 
         */
        public void setNextTransactionStart(long value) {
            this.nextTransactionStart = value;
        }

        /**
         * Gets the value of the numberOfTransactions property.
         * 
         */
        public int getNumberOfTransactions() {
            return numberOfTransactions;
        }

        /**
         * Sets the value of the numberOfTransactions property.
         * 
         */
        public void setNumberOfTransactions(int value) {
            this.numberOfTransactions = value;
        }

        /**
         * Gets the value of the outputDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the outputDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOutputDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails }
         * 
         * 
         */
        public List<AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails> getOutputDetails() {
            if (outputDetails == null) {
                outputDetails = new ArrayList<AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails>();
            }
            return this.outputDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TransactionDateV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99999999"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionTimeV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="999999"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionSRCECODEV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionSRCEV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="20"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionAMTV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__decimal">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99999999999.99"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionCRINDV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionTypeCodeV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionTypeV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="20"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionBranchV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__short">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="9999"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionNarrativeV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="40"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionSerialNoV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__long">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="9999999999999"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionSourceV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PICX__string">
         *               &lt;maxLength value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TransactionEffDateV2">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.ibm.com/dfdl/CobolDataDefinitionFormat}PIC9-Display-Zoned__int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99999999"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transactionDateV2",
            "transactionTimeV2",
            "transactionSRCECODEV2",
            "transactionSRCEV2",
            "transactionAMTV2",
            "transactionCRINDV2",
            "transactionTypeCodeV2",
            "transactionTypeV2",
            "transactionBranchV2",
            "transactionNarrativeV2",
            "transactionSerialNoV2",
            "transactionSourceV2",
            "transactionEffDateV2"
        })
        public static class OutputDetails {

            @XmlElement(name = "TransactionDateV2", defaultValue = "0")
            protected long transactionDateV2;
            @XmlElement(name = "TransactionTimeV2", defaultValue = "0")
            protected long transactionTimeV2;
            @XmlElement(name = "TransactionSRCECODEV2", required = true, defaultValue = " ")
            protected String transactionSRCECODEV2;
            @XmlElement(name = "TransactionSRCEV2", required = true, defaultValue = " ")
            protected String transactionSRCEV2;
            @XmlElement(name = "TransactionAMTV2", required = true, defaultValue = "0")
            protected BigDecimal transactionAMTV2;
            @XmlElement(name = "TransactionCRINDV2", required = true, defaultValue = " ")
            protected String transactionCRINDV2;
            @XmlElement(name = "TransactionTypeCodeV2", defaultValue = "0")
            protected int transactionTypeCodeV2;
            @XmlElement(name = "TransactionTypeV2", required = true, defaultValue = " ")
            protected String transactionTypeV2;
            @XmlElement(name = "TransactionBranchV2", defaultValue = "0")
            protected int transactionBranchV2;
            @XmlElement(name = "TransactionNarrativeV2", required = true, defaultValue = " ")
            protected String transactionNarrativeV2;
            @XmlElement(name = "TransactionSerialNoV2", defaultValue = "0")
            protected long transactionSerialNoV2;
            @XmlElement(name = "TransactionSourceV2", required = true, defaultValue = " ")
            protected String transactionSourceV2;
            @XmlElement(name = "TransactionEffDateV2", defaultValue = "0")
            protected long transactionEffDateV2;

            /**
             * Gets the value of the transactionDateV2 property.
             * 
             */
            public long getTransactionDateV2() {
                return transactionDateV2;
            }

            /**
             * Sets the value of the transactionDateV2 property.
             * 
             */
            public void setTransactionDateV2(long value) {
                this.transactionDateV2 = value;
            }

            /**
             * Gets the value of the transactionTimeV2 property.
             * 
             */
            public long getTransactionTimeV2() {
                return transactionTimeV2;
            }

            /**
             * Sets the value of the transactionTimeV2 property.
             * 
             */
            public void setTransactionTimeV2(long value) {
                this.transactionTimeV2 = value;
            }

            /**
             * Gets the value of the transactionSRCECODEV2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionSRCECODEV2() {
                return transactionSRCECODEV2;
            }

            /**
             * Sets the value of the transactionSRCECODEV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionSRCECODEV2(String value) {
                this.transactionSRCECODEV2 = value;
            }

            /**
             * Gets the value of the transactionSRCEV2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionSRCEV2() {
                return transactionSRCEV2;
            }

            /**
             * Sets the value of the transactionSRCEV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionSRCEV2(String value) {
                this.transactionSRCEV2 = value;
            }

            /**
             * Gets the value of the transactionAMTV2 property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTransactionAMTV2() {
                return transactionAMTV2;
            }

            /**
             * Sets the value of the transactionAMTV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTransactionAMTV2(BigDecimal value) {
                this.transactionAMTV2 = value;
            }

            /**
             * Gets the value of the transactionCRINDV2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionCRINDV2() {
                return transactionCRINDV2;
            }

            /**
             * Sets the value of the transactionCRINDV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionCRINDV2(String value) {
                this.transactionCRINDV2 = value;
            }

            /**
             * Gets the value of the transactionTypeCodeV2 property.
             * 
             */
            public int getTransactionTypeCodeV2() {
                return transactionTypeCodeV2;
            }

            /**
             * Sets the value of the transactionTypeCodeV2 property.
             * 
             */
            public void setTransactionTypeCodeV2(int value) {
                this.transactionTypeCodeV2 = value;
            }

            /**
             * Gets the value of the transactionTypeV2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionTypeV2() {
                return transactionTypeV2;
            }

            /**
             * Sets the value of the transactionTypeV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionTypeV2(String value) {
                this.transactionTypeV2 = value;
            }

            /**
             * Gets the value of the transactionBranchV2 property.
             * 
             */
            public int getTransactionBranchV2() {
                return transactionBranchV2;
            }

            /**
             * Sets the value of the transactionBranchV2 property.
             * 
             */
            public void setTransactionBranchV2(int value) {
                this.transactionBranchV2 = value;
            }

            /**
             * Gets the value of the transactionNarrativeV2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionNarrativeV2() {
                return transactionNarrativeV2;
            }

            /**
             * Sets the value of the transactionNarrativeV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionNarrativeV2(String value) {
                this.transactionNarrativeV2 = value;
            }

            /**
             * Gets the value of the transactionSerialNoV2 property.
             * 
             */
            public long getTransactionSerialNoV2() {
                return transactionSerialNoV2;
            }

            /**
             * Sets the value of the transactionSerialNoV2 property.
             * 
             */
            public void setTransactionSerialNoV2(long value) {
                this.transactionSerialNoV2 = value;
            }

            /**
             * Gets the value of the transactionSourceV2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionSourceV2() {
                return transactionSourceV2;
            }

            /**
             * Sets the value of the transactionSourceV2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionSourceV2(String value) {
                this.transactionSourceV2 = value;
            }

            /**
             * Gets the value of the transactionEffDateV2 property.
             * 
             */
            public long getTransactionEffDateV2() {
                return transactionEffDateV2;
            }

            /**
             * Sets the value of the transactionEffDateV2 property.
             * 
             */
            public void setTransactionEffDateV2(long value) {
                this.transactionEffDateV2 = value;
            }

        }

    }

}
