//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 02:32:19 PM IST 
//


package com.anz.cobolTransform.transform.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anz.cobolTransform.transform.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AcctTrnInqCTMRsp_QNAME = new QName("", "AcctTrnInqCTMRsp");
    private final static QName _AcctTrnInqCTMReq_QNAME = new QName("", "AcctTrnInqCTMReq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anz.cobolTransform.transform.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMRsp }
     * 
     */
    public AcctTrnInqCTMRsp createAcctTrnInqCTMRsp() {
        return new AcctTrnInqCTMRsp();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMRsp.ServiceResponseMsg }
     * 
     */
    public AcctTrnInqCTMRsp.ServiceResponseMsg createAcctTrnInqCTMRspServiceResponseMsg() {
        return new AcctTrnInqCTMRsp.ServiceResponseMsg();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMReq }
     * 
     */
    public AcctTrnInqCTMReq createAcctTrnInqCTMReq() {
        return new AcctTrnInqCTMReq();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMRsp.OutputHeader }
     * 
     */
    public AcctTrnInqCTMRsp.OutputHeader createAcctTrnInqCTMRspOutputHeader() {
        return new AcctTrnInqCTMRsp.OutputHeader();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMRsp.SecondaryHdr }
     * 
     */
    public AcctTrnInqCTMRsp.SecondaryHdr createAcctTrnInqCTMRspSecondaryHdr() {
        return new AcctTrnInqCTMRsp.SecondaryHdr();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails }
     * 
     */
    public AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails createAcctTrnInqCTMRspServiceResponseMsgOutputDetails() {
        return new AcctTrnInqCTMRsp.ServiceResponseMsg.OutputDetails();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMReq.InputHeader }
     * 
     */
    public AcctTrnInqCTMReq.InputHeader createAcctTrnInqCTMReqInputHeader() {
        return new AcctTrnInqCTMReq.InputHeader();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMReq.SecondaryHeader }
     * 
     */
    public AcctTrnInqCTMReq.SecondaryHeader createAcctTrnInqCTMReqSecondaryHeader() {
        return new AcctTrnInqCTMReq.SecondaryHeader();
    }

    /**
     * Create an instance of {@link AcctTrnInqCTMReq.ServiceRequestMsg }
     * 
     */
    public AcctTrnInqCTMReq.ServiceRequestMsg createAcctTrnInqCTMReqServiceRequestMsg() {
        return new AcctTrnInqCTMReq.ServiceRequestMsg();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcctTrnInqCTMRsp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcctTrnInqCTMRsp")
    public JAXBElement<AcctTrnInqCTMRsp> createAcctTrnInqCTMRsp(AcctTrnInqCTMRsp value) {
        return new JAXBElement<AcctTrnInqCTMRsp>(_AcctTrnInqCTMRsp_QNAME, AcctTrnInqCTMRsp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcctTrnInqCTMReq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcctTrnInqCTMReq")
    public JAXBElement<AcctTrnInqCTMReq> createAcctTrnInqCTMReq(AcctTrnInqCTMReq value) {
        return new JAXBElement<AcctTrnInqCTMReq>(_AcctTrnInqCTMReq_QNAME, AcctTrnInqCTMReq.class, null, value);
    }

}
