//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 08:58:39 AM IST 
//


package com.anz.AcctTrnInq.transform.pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anz.AcctTrnInq.transform.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anz.AcctTrnInq.transform.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link AcctTrnInqRs }
     * 
     */
    public AcctTrnInqRs createAcctTrnInqRs() {
        return new AcctTrnInqRs();
    }

    /**
     * Create an instance of {@link ANZAcctIdType }
     * 
     */
    public ANZAcctIdType createANZAcctIdType() {
        return new ANZAcctIdType();
    }

    /**
     * Create an instance of {@link CustIdType }
     * 
     */
    public CustIdType createCustIdType() {
        return new CustIdType();
    }

    /**
     * Create an instance of {@link SelRangeDtType }
     * 
     */
    public SelRangeDtType createSelRangeDtType() {
        return new SelRangeDtType();
    }

    /**
     * Create an instance of {@link SelRangeChqNumType }
     * 
     */
    public SelRangeChqNumType createSelRangeChqNumType() {
        return new SelRangeChqNumType();
    }

    /**
     * Create an instance of {@link SelRangeCurAmtType }
     * 
     */
    public SelRangeCurAmtType createSelRangeCurAmtType() {
        return new SelRangeCurAmtType();
    }

    /**
     * Create an instance of {@link TrnFiltersType }
     * 
     */
    public TrnFiltersType createTrnFiltersType() {
        return new TrnFiltersType();
    }

    /**
     * Create an instance of {@link RecCtrlOutType }
     * 
     */
    public RecCtrlOutType createRecCtrlOutType() {
        return new RecCtrlOutType();
    }

    /**
     * Create an instance of {@link BankAcctTrnRecType }
     * 
     */
    public BankAcctTrnRecType createBankAcctTrnRecType() {
        return new BankAcctTrnRecType();
    }

    /**
     * Create an instance of {@link AcctTrnInqRq }
     * 
     */
    public AcctTrnInqRq createAcctTrnInqRq() {
        return new AcctTrnInqRq();
    }

    /**
     * Create an instance of {@link ANZTraceInfoType }
     * 
     */
    public ANZTraceInfoType createANZTraceInfoType() {
        return new ANZTraceInfoType();
    }

    /**
     * Create an instance of {@link RecCtrlInType }
     * 
     */
    public RecCtrlInType createRecCtrlInType() {
        return new RecCtrlInType();
    }

    /**
     * Create an instance of {@link CardholderIdType }
     * 
     */
    public CardholderIdType createCardholderIdType() {
        return new CardholderIdType();
    }

    /**
     * Create an instance of {@link PostAddrType }
     * 
     */
    public PostAddrType createPostAddrType() {
        return new PostAddrType();
    }

    /**
     * Create an instance of {@link ComAnzANZAcctIdType }
     * 
     */
    public ComAnzANZAcctIdType createComAnzANZAcctIdType() {
        return new ComAnzANZAcctIdType();
    }

    /**
     * Create an instance of {@link BankInfoType }
     * 
     */
    public BankInfoType createBankInfoType() {
        return new BankInfoType();
    }

    /**
     * Create an instance of {@link RefInfoType }
     * 
     */
    public RefInfoType createRefInfoType() {
        return new RefInfoType();
    }

    /**
     * Create an instance of {@link StatusType.AdditionalStatus }
     * 
     */
    public StatusType.AdditionalStatus createStatusTypeAdditionalStatus() {
        return new StatusType.AdditionalStatus();
    }

}
